backend:
  name: github
  repo: lmcorreia/portuguese_women_tech # Path to your Github repository
  branch: feature/4_go_hugo # Branch to update (master by default)

media_folder: "/static/images/profiles" # Folder where user uploaded files should go
public_folder: "/images/profiles"

collections: # A list of collections the CMS should be able to edit
  - name: "profile" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Profile" # Used in the UI, ie.: "New Post"
    folder: "content/profiles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "description", widget: "string"}
      - {label: "Time in Tech", name: "timeInTech", widget: "string"}
      - {label: "Place of Origin", name: "placeOfOrigin", widget: "string"}
      - label: "Social Links"
        name: "socialLinks"
        widget: "list"
        fields:
          - label: "Social Network (twitter / linkedin / medium)"
            name: "name"
            widget: "string"
          - label: "URL"
            name: "url"
            widget: "string"
      - {label: "Profile picture", name: "image", widget: "image"}


      - {label: "Body", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "General settings"
        file: "config.toml"
        fields:
          - {label: "Main site title", name: "title", widget: "string"}
          - {label: "Main site theme", name: "theme", widget: "string"}